rakedevelopment:
  adapter: mysql2
  database: ringsail_development
  encoding: utf8
  collation: utf8_unicode_ci  
  host: localhost
test:
  adapter: mysql2
  database: ringsail_test
  encoding: utf8
  collation: utf8_unicode_ci  
  host: localhost
production:
  adapter: mysql2
  database: ringsail_production
  encoding: utf8
  collation: utf8_unicode_ci
  host: localhost
